# Generated by Django 6.0.1 on 2026-01-22 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_activationcode_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stream_url', models.URLField(max_length=500)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(default='General', max_length=50)),
                ('country', models.CharField(default='International', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
