# Generated by Django 6.0.1 on 2026-01-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_playlist_channel_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='stream_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='m3u_url',
            field=models.URLField(max_length=1000),
        ),
    ]
