# Generated by Django 6.0.1 on 2026-01-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_channel_logo_url_alter_channel_stream_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
