# Generated by Django 6.0.1 on 2026-01-23 01:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_activationcode_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPGProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='api.channel')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['channel', 'start_time', 'end_time'], name='api_epgprog_channel_69f22d_idx')],
            },
        ),
    ]
