# Generated by Django 6.0.1 on 2026-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_epgprogram'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='epgprogram',
            name='api_epgprog_channel_69f22d_idx',
        ),
        migrations.AlterField(
            model_name='channel',
            name='logo_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='stream_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.DeleteModel(
            name='EPGProgram',
        ),
    ]
