# Generated by Django 6.0.1 on 2026-01-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_device_last_ip_device_user_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='episode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='series_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
