# Generated by Django 6.0.1 on 2026-01-24 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_channel_episode_channel_season_channel_series_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(default=0)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='api.channel')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='api.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='api_channel_timesta_6859d2_idx'), models.Index(fields=['channel'], name='api_channel_channel_508f0e_idx')],
            },
        ),
    ]
