# Generated by Django(Manually)

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_series_channel_language_alter_channel_stream_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationcode',
            name='client_reference',
            field=models.CharField(blank=True, help_text='Manual reference for client identification', max_length=100, null=True),
        ),
    ]
