# Generated by Django(Manually)

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_activationcode_client_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelview',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channelview',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='channelview',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
